### ISSUE TITLE
Review practice `expect(true).toBe(true)`

### ISSUE THREAD

**Issue by elgalu** [selfrefactor/Protractor-testing-patterns#1]
I think you should review this practice:

> Use the expect(true).toBe(true) to assure that your filtering works as you expected

So would replace this code
```js
if(currentElement.getText()==="I was looking for you"){
  expect(true).toBe(true)
}
```

With:
```js
expect(currentElement.getText()).toEqual("I was looking for you")
```

Also `currentElement.getText()==="I was looking for you"` doesn't work in the first place because you're missing `then` i.e. it will always evaluate to true because a promise is never false.

**Comment by selfrefactor** [comment]
It is a bad tip, so I remove it all along, but thank you for your advice.
